// 실제 캡처의 문자 경계(이미지 너비·높이 대비 %)와 코드 확인된 작업 절차.
const accurateBoxes=[[44,50.8,35.3,7.5],[56.6,48.7,12.4,4.5],[46.5,46.8,7.2,2.7],[81.5,52.6,7.2,2.7],[46.5,49.5,7.6,2.8],[81.5,55.2,7.5,2.8],[58,56.1,13,4.5]];
document.querySelectorAll('[data-box]').forEach((mark,i)=>mark.dataset.box=accurateBoxes[i].join(','));
const exampleValues=[['START → END','왼쪽 초록 점 → 오른쪽 빨강 점'],['K-ST-01-0107','관번호'],['40.92 / 40.65 m','상류 / 하류 지반고'],['38.04 / 37.66 m','상류 / 하류 관저고'],['450 mm · 80.4 m','관경 · 연장 (S=0.5는 이 두 필드에 포함하지 않음)']];
const example=document.createElement('div');example.className='example-value';example.setAttribute('aria-live','polite');document.querySelector('.collect-result').after(example);
function updateExample(){const [value,label]=exampleValues[collectIndex];example.innerHTML=`<small>캡처 원문에서 읽는 예시 · ${label}</small><strong>${value}</strong><span>아래 수집 규칙에 따라 연결되는 값입니다. 별도 DETAIL 캡처를 재현한 화면은 아닙니다.</span>`;document.querySelectorAll('[data-collect]').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('active'))));positionCollectMarks();}
document.querySelector('#collect-tabs').addEventListener('click',updateExample);document.querySelector('#collect-prev').addEventListener('click',updateExample);document.querySelector('#collect-next').addEventListener('click',updateExample);updateExample();
const operations={
 settings:{title:'수집 전에 레이어와 표기를 맞추기',image:'FlowWork_settings_screen.png',steps:[['도면에서 원본 객체 확인','관로선과 관번호·지반고·관저고·제원 문자를 하나씩 선택하고 CAD 속성에서 레이어 이름을 확인합니다. 화면 색상이 같다는 이유로 같은 레이어라고 판단하지 마세요.','각 항목의 실제 레이어 이름을 확보합니다.'],['설정 메뉴에서 대응시키기','관로선, 관번호, 지반고, 관저고, 제원 레이어를 각각 지정합니다. GH, INV, Ø, L 등 도면의 실제 표기와 접두어 설정도 대조합니다.','지반고와 관저고 레이어를 서로 바꾸지 않았는지 확인합니다.'],['검색 범위 확인','관번호·제원은 관로선 주변, 지반고·관저고는 양 끝점 주변을 확인합니다. 반경을 크게 하면 이웃 관로의 문자도 후보가 될 수 있습니다.','누락된 문자 한 개 때문에 전체 검색 범위를 무조건 넓히지 않습니다.'],['수집하고 표본 검토','설정을 적용한 뒤 도면 정보 수집을 실행합니다. 총 관로 수와 대표 관로 한 개의 원본 문자를 결과와 대조합니다.','수량뿐 아니라 관번호·양 끝 표고·관경·연장이 맞아야 합니다.']]},
 mapping:{title:'지반고·관저고 문자를 직접 지정하기',image:'FlowWork_direct_mapping_candidates.png',steps:[['대상과 끝점 확인','관로 목록에서 대상을 선택하고 도면의 START/END를 확인합니다. 상류는 START, 하류는 END에 대응합니다.','다른 관로의 문자를 지정하지 않도록 관번호부터 맞춥니다.'],['수정할 필드 선택','상류 지반고, 하류 지반고, 상류 관저고, 하류 관저고 중 해당 직접 지정 기능을 선택합니다. CAD 명령창의 문자 선택 안내를 읽습니다.','M-GL은 지반고, M-INV는 관저고의 수동 연결 표시입니다.'],['CAD 원본 문자 선택','원하는 높이가 적힌 텍스트 객체를 클릭합니다. 선택 중 팔레트가 흐려지는 것은 선택 모드의 동작입니다. 취소하려면 Esc를 누릅니다.','숫자를 새로 입력하는 기능이 아니라 원본 문자 객체를 연결합니다.'],['자동 재수집 결과 확인','선택 완료 후 자동 재수집됩니다. 수집값과 진단 메시지, 연결된 문자를 다시 확인합니다. 잘못 지정했다면 같은 필드에서 올바른 문자를 다시 지정합니다.','경고가 없어졌다는 사실만으로 끝내지 말고 원본 값과 일치하는지 확인한 뒤 DWG를 저장합니다.']]},
 reverse:{title:'역경사 경고를 확인하고 방향 판단하기',image:'FlowWork_direct_mapping_candidates.png',steps:[['관저고 원문 확인','START와 END에 연결된 관저고가 실제 해당 끝점의 문자인지 봅니다. 문자가 잘못 연결됐다면 먼저 수동 매핑을 수정합니다.','역경사 경고가 곧 방향 오류를 뜻하지는 않습니다.'],['설계 방향과 비교','설계상 흐름 방향을 확인하고 현재 START → END와 비교합니다. 원본 값도 방향도 맞으면 설계 검토가 필요합니다.','경고를 없애기 위한 목적으로 방향을 바꾸지 않습니다.'],['방향 변경 실행','현재 방향만 반대라고 확인된 경우 선택 관로의 방향 변경 기능을 실행합니다. 실제 CAD 선의 방향을 반전하고 상·하류 수동 매핑을 교환합니다.','원본 표고 문자의 숫자를 고치는 기능이 아닙니다.'],['반전 결과 검토','자동 재수집 후 START/END, 상·하류 연결과 지반고·관저고를 확인합니다. 관번호와 제원도 동일 대상인지 대조합니다.','정확한 결과를 확인한 뒤 DWG를 저장하고 필요하면 결과를 다시 내보냅니다.']]},
 save:{title:'DWG 저장과 결과 내보내기',image:'FlowWork_menu_screen.png',steps:[['현재 도면과 결과 확인','수집한 도면과 현재 활성 도면이 같은지 확인합니다. CAD 문자를 수정했다면 다시 수집하고 임시값·누락 경고를 검토합니다.','숫자가 있어도 연장 누락·관경 누락 경고가 있으면 확인이 필요합니다.'],['DWG 저장','AutoCAD에서 DWG를 저장해 선 방향 변경과 수동 매핑 정보를 보존합니다. 다른 도면으로 전환하기 전에 저장 여부를 확인합니다.','JSON이나 CSV 내보내기가 DWG 저장을 대신하지 않습니다.'],['용도에 맞게 내보내기','JSON은 시스템 이름·스키마 버전·관로 데이터를 담습니다. CSV는 관로번호, 연결, 관경, 길이, 양 끝 표고와 오류개수를 표로 검토할 때 사용합니다.','저장 경로와 파일 이름을 확인합니다.'],['다시 작업할 때','DWG를 다시 열어 수집하고 대표 관로의 매핑과 방향을 확인합니다. 원본 문자를 삭제·교체했다면 수동 연결이 유효한지 진단을 확인합니다.','변경 이후의 최신 결과가 필요하면 JSON·CSV도 다시 내보냅니다.']]},
 count:{title:'수집 수량이 예상보다 적을 때',image:'FlowWork_settings_screen.png',steps:[['대상 도면 확인','현재 도면과 수집한 도면이 같은지 확인합니다. 다른 도면의 결과를 보고 있다면 해당 도면에서 다시 수집합니다.','비교 대상은 같은 도면이어야 합니다.'],['관로선 레이어 확인','빠진 관로선의 CAD 속성을 열어 설정된 관로선 레이어와 비교합니다. 문자 레이어 설정만 바꿔서는 빠진 관로가 추가되지 않습니다.','실제 객체의 종류와 레이어를 확인합니다.'],['재수집 후 비교','설정을 적용하고 수집합니다. 총 수량과 빠졌던 관로가 목록에 나타나는지 확인합니다.','수량이 늘어도 원본과 잘못 매칭된 관로가 없는지 표본 검토합니다.']]},
 joint:{title:'관로 끝점이 떨어져 있을 때',image:'FlowWork_0116_centered.png',steps:[['끝점 확대','진단 대상 관로와 이웃 관로의 끝점을 확대합니다. 화면상 겹쳐 보여도 좌표가 다를 수 있습니다.','실제로 연결되어야 하는 두 끝점인지 설계를 확인합니다.'],['CAD에서 연결 수정','연결되어야 하는 끝점이라면 CAD 객체 스냅으로 정확하게 맞춥니다. 가까운 다른 관로에 연결하지 않도록 주의합니다.','현재 추출 코드의 노드 병합 기준은 0.05이며 검색 반경과 별개입니다.'],['연결 결과 재확인','도면 정보 수집을 다시 실행하고 상·하류 연결과 접점 경고를 확인합니다.','검색 반경을 늘리는 것으로 선 끝점의 틈이 수정되지는 않습니다.']]}
};
const section=document.createElement('section');section.className='view operations-view';section.dataset.view='operations';section.hidden=true;
section.innerHTML='<div class="view-heading"><div><span>작업별 상세 안내</span><h2>확인하고, 조작하고, 결과 비교하기</h2></div></div><div class="operation-tabs"></div><div class="operation-layout"><div><img id="operation-image" alt="작업에 참고할 실제 FlowWork 화면"><p class="image-note">기존 실제 캡처 · 각 단계의 클릭 결과를 재현한 영상은 아닙니다.</p><nav id="operation-steps" aria-label="작업 단계"></nav></div><article aria-live="polite"><small id="operation-progress"></small><h2 id="operation-title"></h2><p id="operation-body"></p><div class="result-check"><b>확인할 결과</b><p id="operation-check"></p></div><div class="operation-controls"><button id="operation-prev">이전</button><button id="operation-next">다음</button></div></article></div>';
document.querySelector('main').append(section);views.push(section);
for(const [key,label] of [['settings','수집 설정'],['mapping','수동 매핑'],['reverse','방향 판단'],['save','저장'],['count','수량 부족'],['joint','접점 이격']]){const button=document.createElement('button');button.textContent=label;button.dataset.operation=key;button.onclick=()=>showOperation(key,0);section.querySelector('.operation-tabs').append(button);}
let operationKey='settings',operationStep=0;
function showOperation(key,step){operationKey=key;const item=operations[key];operationStep=Math.max(0,Math.min(step,item.steps.length-1));const [title,body,check]=item.steps[operationStep];document.querySelector('#operation-image').src='../manual/assets/images/'+item.image;document.querySelector('#operation-progress').textContent=`${item.title} · ${operationStep+1} / ${item.steps.length}`;document.querySelector('#operation-title').textContent=title;document.querySelector('#operation-body').textContent=body;document.querySelector('#operation-check').textContent=check;document.querySelectorAll('[data-operation]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.operation===key)));const steps=document.querySelector('#operation-steps');steps.replaceChildren();item.steps.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s[0]}`;b.setAttribute('aria-current',i===operationStep?'step':'false');b.onclick=()=>showOperation(key,i);steps.append(b);});document.querySelector('#operation-prev').disabled=operationStep===0;document.querySelector('#operation-next').disabled=operationStep===item.steps.length-1;}
document.querySelector('#operation-prev').onclick=()=>showOperation(operationKey,operationStep-1);document.querySelector('#operation-next').onclick=()=>showOperation(operationKey,operationStep+1);
const link=document.createElement('a');link.href='#operations';link.textContent='設定·수정·저장'.replace('設定','설정');document.querySelector('.mode-nav').append(link);const menuLink=link.cloneNode(true);menuLink.onclick=()=>drawer.hidden=true;drawer.append(menuLink);
document.querySelectorAll('[data-problem]').forEach(button=>button.onclick=()=>{showOperation(button.dataset.problem==='missing'?'mapping':button.dataset.problem,0);location.hash='operations';});
window.addEventListener('hashchange',()=>requestAnimationFrame(()=>{positionLearnFocus();positionCollectMarks();}));new ResizeObserver(()=>{positionLearnFocus();positionCollectMarks();}).observe(document.querySelector('#workspace'));
showOperation('settings',0);route();requestAnimationFrame(positionCollectMarks);
